blueprint:
  name: Divera alarm automation
  description: Trigger some actions when a new Divera alarm is triggered.
  domain: automation
  input:
    divera_sensor:
      name: Divera sensor
      description: The sensor which show the current alarm state
      selector:
        entity:
          integration: divera
          domain: sensor
    abort_keyword:
      name: (optional) Abort keyword
      description: "(optional) Alarm title/keyword when the action should not be triggered. For example: Probealarm"
      selector:
        text: {}
    target_action:
      name: Action
      description: What should be done, when a new divera alarm is trigged?
      selector:
        action: {}
trigger:
  platform: state
  entity_id: !input divera_sensor
  not_to: 
    - unknown
    - !input 'abort_keyword'
action:
- choose:
  default: !input 'target_action'
