name: 🐞 Bug Report
description: Report a bug or issue with the integration.
title: "<title>"
labels: "bug"
assignees: "@fwmarcel"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please fill out the form below to help us identify and fix the issue.

  - type: input
    id: title
    attributes:
      label: Bug Title
      description: Provide a short and descriptive title for the bug.
      placeholder: e.g., "Error when connecting to Divera"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the issue in detail. Include steps to reproduce, what you expected to happen, and what actually happened.
      placeholder: >
        1. Steps to reproduce:
        2. What I expected:
        3. What actually happened:
    validations:
      required: true

  - type: input
    id: home_assistant_version
    attributes:
      label: Home Assistant Version
      description: Specify the version of Home Assistant you are using (e.g., 2024.12.1).
      placeholder: e.g., 2024.12.1
    validations:
      required: true

  - type: input
    id: divera_integration_version
    attributes:
      label: Divera Integration Version
      description: Specify the version of the Divera integration you are using.
      placeholder: e.g., 1.3.0
    validations:
      required: true

  - type: dropdown
    id: divera_version
    attributes:
      label: Divera Version
      description: Specify the version of the Divera you are using.
      options:
        - Free
        - Alarm
        - Pro
        - Self Hosting
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Error Messages
      description: Paste any relevant logs or error messages. Make sure to redact any sensitive information.
      placeholder: >
        Include relevant logs or error messages here.
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Provide any other details that might help us diagnose the issue.
      placeholder: >
        Include any additional context here.
    validations:
      required: true
