# https://www.home-assistant.io/integrations/default_config/

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.divera: debug

debugpy:
  start: false
  wait: false
